spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://postgres:5432/${NOTIFICATION_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: com.ratnesh.connecthub.*

server:
  servlet:
    context-path: /notifications
  port: 9070

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

jwt:
  secretKey: ${JWT_SECRET}