spring:
  application:
    name: connection-service

  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: com.ratnesh.connecthub.*

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 9010
  servlet:
    context-path: /connections

jwt:
  secretKey: ${JWT_SECRET}