spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres:5432/${USER_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 9030
  servlet:
    context-path: /users

jwt:
  secretKey: ${JWT_SECRET}