spring:
  application:
    name: discovery-server



eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



jwt.secretKey: 9d3f6c8a1b2e4f5g7h8j9k0lmnopqrstuv

server:
  port: 8761